{% set version = '0.1.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytext
  version: {{ version|replace("-", "_") }}

source:
  fn: tidytext_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidytext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytext/tidytext_{{ version }}.tar.gz
  sha256: 743bb89d40ff032350acbc7db590977cc1c3a4dac328b08a05ca2d7cc3818383

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: readr, tidyr, XML, tm, quanteda, knitr, rmarkdown, ggplot2, reshape2, wordcloud, topicmodels, NLP, scales, gutenbergr, testthat, mallet, stm
requirements:
  build:

  host:
    - r-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stopwords
    - r-stringr
    - r-tokenizers

  run:
    - r-base
    - r-matrix
    - r-broom
    - r-dplyr
    - r-hunspell
    - r-janeaustenr
    - r-purrr >=0.1.1
    - r-rlang
    - r-stopwords
    - r-stringr
    - r-tokenizers

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tidytext')"           # [not win]
    - "\"%R%\" -e \"library('tidytext')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/juliasilge/tidytext
  license: MIT + file LICENSE
  summary: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and
    other tidy tools.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: tidytext
# Type: Package
# Title: Text Mining using 'dplyr', 'ggplot2', and Other Tidy Tools
# Version: 0.1.8
# Authors@R: c(person("Gabriela", "De Queiroz", role = c("ctb"), email = "gabidequeiroz@gmail.com"), person("Os", "Keyes", role = c("ctb"), email = "ironholds@gmail.com", comment = c(ORCID = "0000-0001-5196-609X")), person("Kanishka", "Misra", role = c("ctb"), email = "kmisra@purdue.edu"), person("David", "Robinson", role = c("aut"), email = "admiral.david@gmail.com"), person("Julia", "Silge", role = c("aut", "cre"),  email = "julia.silge@gmail.com",  comment = c(ORCID = "0000-0002-3671-836X")))
# Description: Text mining for word processing and sentiment analysis using 'dplyr', 'ggplot2', and other tidy tools.
# License: MIT + file LICENSE
# LazyData: TRUE
# URL: http://github.com/juliasilge/tidytext
# BugReports: http://github.com/juliasilge/tidytext/issues
# RoxygenNote: 6.0.1
# Depends: R (>= 2.10)
# Imports: rlang, dplyr, stringr, hunspell, broom, Matrix, tokenizers, janeaustenr, purrr (>= 0.1.1), methods, stopwords
# Suggests: readr, tidyr, XML, tm, quanteda, knitr, rmarkdown, ggplot2, reshape2, wordcloud, topicmodels, NLP, scales, gutenbergr, testthat, mallet, stm
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-03-21 16:02:10 UTC; juliasilge
# Author: Gabriela De Queiroz [ctb], Os Keyes [ctb] (<https://orcid.org/0000-0001-5196-609X>), Kanishka Misra [ctb], David Robinson [aut], Julia Silge [aut, cre] (<https://orcid.org/0000-0002-3671-836X>)
# Maintainer: Julia Silge <julia.silge@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-03-21 22:34:59 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
