travis:
  secure:
    BINSTAR_TOKEN: CS0hY6QbWXwK2cN6d8tjNakTUIEpD5lt0hS70Iq5URfBT4Xxrq8vp8dJEJF0d44XLKQnY/bwJiZHXE3PW578rltBMaQde98bmMnwbCqTzXJc2LW+78X2HXD/kkrCJbLuDuXCKOwBBIv63oGosO5cmsSO9ut4v7F3PV5Ihby8t5tc0F8AAmWTCWagO45onGRLDsxvOgHktkVy216oJsVOWh4moRFjwqGb4D2tnSnrevn9XMSvhIkO6w6UnpVqxLCUWrKqKdyTy0XOExWUwx1tSbKtgietH/LIoKgIl5ExLfyC28RQKpIohFZCxtPKeOYOdUxF6tAFfdxTT10H1PfmCjypHoVEQe2vSaIvSXu0LkRIcC9nKlRPXjhVb7yGDlSBMWBgwG0KYwB+6t3yKhsqtTvqiXh+W/xCz0mnNyGJLoS/A2TqvTr8fd5+RRNIddmbyqodhg6YEJ5rvfzGMlBwxxofvr+hlpOKhc01Ce/+BswCfKb4N1m6hcg/GKmdfJWLYBeBQmat0ddbKTt5GRQHWOjcO4eggjz//gRVC0UFhEGSqp719EaWwZY0zMIvPyFeySybmU//HL4QrDZ0J+ZIqdKGr+vg5MGwMR+he6uIXW/8SBNJcIl8X+UCEmWGC6Y2ZRNubOYy/qzDHNVlWb8I1tY9O1RvH+kiqxvENDEDF6M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
