travis:
  secure:
    BINSTAR_TOKEN: xVCaC/wgyjSkdCMnP8hfjZugVOo3UxsOCgnakFjirTgWB0VAcxmCv576kTHIA7aZL2TlsNKocy5Ih5egpBhvO+TT1tm6vRovf104BYs3oHvvnfW1YTRAJwtBdW+xrqo9ZvFfOdsrOyavHrwr2fEH8sgcLzIh6mUaVtXdHbSbcrKuZur4g95iBzhxDhnui8NMjNoZCJ+LxaJGv4vXvGz8P5ttnOa3X2JiTdYJHDTAhKZxYGA4gzKLMoSC7DfjnRBStAF0aXGTCYtDFLd4lFu1Lc8TCXJsdV7OHkqhE2ZLQhoo7WLlXOVtv98lcaEJkkxY49QlpbjmioOqEreJjmLcqB72goFOUO0LOnKt4gljD+F+W3bfRrz+A4hI3U3j/Q1pmIyGk8cAshYBVA2pb3qAGjrTF0KboB/BEQfNhu+aSmaaHejv2wxL5g9MSPgEmNOESsXNBQo8iHQZQ6PfBB0TTlTNRF4bX3ojEXjrinH+NKweORXSEgV0RcLULSI5VyTwPs7Zvxo3f69UhRceKAWt7T/pNri5MgaGZBlOlbf26aoSayaKLtIUARai76Q2bup/V07SbP7BnobCJ77jxGuK2SvuXPal8vcQG1lsIsqgvTOYqE6NDOxIoEm5ydxEN2QmsrTKv7sJzHgUVjm+34AffnSwT5H/BGz4+NevG+chfDA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
